In [26]:
import pandas as pd
data=pd.read_csv("house_tiny.csv")

In [27]:
data

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [28]:
inputs=data.iloc[:,0:2]

In [29]:
inputs

   NumRooms RoofType
0       NaN      NaN
1       2.0      NaN
2       4.0    Slate
3       NaN      NaN

In [30]:
target=data.iloc[:,2]

In [31]:
target

0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64

In [32]:
inputs=pd.get_dummies(inputs,dummy_na=True)

In [34]:
inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [35]:
mean=inputs.mean()

In [37]:
inputs=inputs.fillna(mean)

In [38]:
inputs

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True